FROM node:latest

WORKDIR /app

COPY package.json yarn.lock /app

RUN yarn

COPY . /app

RUN yarn run build

FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
COPY --from=build /app/dist /var/www/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]